# Generated by Django 2.0.13 on 2019-10-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': True, 'permissions': (('menu_dashboard', '菜单 Dashboard'), ('menu_sqlcheck', '菜单 SQL审核'), ('menu_sqlworkflow', '菜单 SQL上线'), ('menu_sqldataout', '菜单 数据导出'), ('menu_sqlanalyze', '菜单 SQL分析'), ('menu_query', '菜单 SQL查询'), ('menu_sqlquery', '菜单 在线查询'), ('menu_sqloutput', '菜单 在线导出'), ('menu_queryapplylist', '菜单 权限管理'), ('menu_sqloptimize', '菜单 SQL优化'), ('menu_sqladvisor', '菜单 优化工具'), ('menu_slowquery', '菜单 慢查日志'), ('menu_instance', '菜单 实例管理'), ('menu_instance_list', '菜单 实例列表'), ('menu_dbdiagnostic', '菜单 会话管理'), ('menu_param', '菜单 参数配置'), ('menu_data_dictionary', '菜单 数据字典'), ('menu_binlog2sql', '菜单 Binlog2SQL'), ('menu_schemasync', '菜单 SchemaSync'), ('menu_system', '菜单 系统管理'), ('menu_document', '菜单 相关文档'), ('menu_themis', '菜单 数据库审核'), ('sql_submit', '提交SQL上线工单'), ('sql_review', '审核SQL上线工单'), ('sql_execute_for_resource_group', '执行SQL上线工单(资源组粒度)'), ('sql_execute', '执行SQL上线工单(仅自己提交的)'), ('sql_analyze', '执行SQL分析'), ('optimize_sqladvisor', '执行SQLAdvisor'), ('optimize_sqltuning', '执行SQLTuning'), ('optimize_soar', '执行SOAR'), ('query_applypriv', '申请查询权限'), ('query_mgtpriv', '管理查询权限'), ('query_review', '审核查询权限'), ('query_submit', '提交SQL查询'), ('query_all_instances', '可查询所有实例'), ('process_view', '查看会话'), ('process_kill', '终止会话'), ('tablespace_view', '查看表空间'), ('trxandlocks_view', '查看锁信息'), ('param_view', '查看实例参数列表'), ('param_edit', '修改实例参数'))},
        ),
    ]
